name: patient_follow_up
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.12.0
  get: ^4.6.5
  get_storage: ^2.1.1
  permission_handler: ^10.2.0
  crypto: ^3.0.3
  intl: ^0.18.1
  responsive_framework: ^1.0.0
  animated_splash_screen: ^1.1.0
  flutter_svg: ^1.1.4
  lottie: ^2.2.0
  animated_text_kit: ^4.2.2
  logger: ^1.1.0
  flutter_screenutil: ^5.0.2
  path_provider: ^2.0.13
  google_fonts: ^3.0.1
  firebase_core: ^2.7.1
  firebase_auth: ^4.2.10
  image_picker: ^0.8.7
  flutter_image_compress: ^1.1.3
  multi_select_flutter: ^4.1.3
  firebase_crashlytics: ^3.0.16
  change_app_package_name: ^1.1.0
  email_validator: ^2.1.16
  persistent_bottom_nav_bar: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/lottie/
    - assets/fonts/
    - assets/img/
    - assets/icons/
    - assets/svg/
    #- .env

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway.ttf